### ISSUE TITLE
Trying to setup testing on mac. 

### ISSUE THREAD

**Issue by joshchernoff** [route/mogrify#67]
Trying to get some testing working but running into issue. 

As far as I can tell I have  ImageMagick 7.0.8-21  installed. 
```elixir
~/Dev/elixir/mogrify master
❯ convert -version

Version: ImageMagick 7.0.8-21 Q16 x86_64 2018-12-28 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib freetype jng jp2 jpeg lcms ltdl lzma png tiff webp xml zlib
```

But when trying to run the tests. 

```
~/Dev/elixir/mogrify master
❯ mix test
....

  1) test pango by using single quotes (MogrifyTest)
     test/mogrify_test.exs:154
     Assertion with == failed
     code:  assert File.exists?(path) == true
     left:  false
     right: true
     stacktrace:
       test/mogrify_test.exs:162: (test)

......

  2) test binary output (MogrifyTest)
     test/mogrify_test.exs:192
     ** (MatchError) no match of right hand side value: {"convert: unable to open image '<span foreground=\"yellow\">hello test</span>': No such file or directory @ error/blob.c/OpenBlob/3492.\nconvert: no decode delegate for this image format `PANGO' @ error/constitute.c/ReadImage/556.\nconvert: no images defined `png:-' @ error/convert.c/ConvertImageCommand/3300.\n", 1}
     code: |> create(buffer: true)
     stacktrace:
       (mogrify) lib/mogrify.ex:48: Mogrify.create/2
       test/mogrify_test.exs:197: (test)

........

  3) test pango success (MogrifyTest)
     test/mogrify_test.exs:140
     Assertion with == failed
     code:  assert File.exists?(path) == true
     left:  false
     right: true
     stacktrace:
       test/mogrify_test.exs:148: (test)



  4) test binary output using into: IO.stream/2 (MogrifyTest)
     test/mogrify_test.exs:202
     ** (MatchError) no match of right hand side value: {%IO.Stream{device: :standard_io, line_or_bytes: :line, raw: true}, 1}
     code: capture_io(fn ->
     stacktrace:
       (mogrify) lib/mogrify.ex:48: Mogrify.create/2
       test/mogrify_test.exs:209: anonymous fn/0 in MogrifyTest."test binary output using into: IO.stream/2"/1
       (ex_unit) lib/ex_unit/capture_io.ex:150: ExUnit.CaptureIO.do_capture_io/2
       (ex_unit) lib/ex_unit/capture_io.ex:120: ExUnit.CaptureIO.do_capture_io/3
       test/mogrify_test.exs:204: (test)

.

  5) test pango by wrapping in <markup /> tags (MogrifyTest)
     test/mogrify_test.exs:168
     Assertion with == failed
     code:  assert File.exists?(path) == true
     left:  false
     right: true
     stacktrace:
       test/mogrify_test.exs:176: (test)

..

  6) test binary output buffer matches file output (MogrifyTest)
     test/mogrify_test.exs:217
     ** (MatchError) no match of right hand side value: {"convert: unable to open image '<span foreground=\"yellow\">hello test</span>': No such file or directory @ error/blob.c/OpenBlob/3492.\nconvert: no decode delegate for this image format `PANGO' @ error/constitute.c/ReadImage/556.\nconvert: no images defined `png:-' @ error/convert.c/ConvertImageCommand/3300.\n", 1}
     code: result1 = image |> custom("stdout", "png:-") |> create(buffer: true)
     stacktrace:
       (mogrify) lib/mogrify.ex:48: Mogrify.create/2
       test/mogrify_test.exs:222: (test)

.............

Finished in 2.8 seconds
40 tests, 6 failures
````

Thoughts?

**Comment by talklittle** [comment]
Pango is a GNOME GTK thing so those failures can be ignored on Mac. We should probably disable those tests when Pango is not installed.

**Comment by joshchernoff** [comment]
So in that regard I was trying to get the test running for this module so that I can learn to add like testing for my project. Any ideas how I would get a test running for something like. 

```
defmodule PolymorphicProductions.Assets.Processor do
  import Mogrify

  def scale_image(path) do
    path
    |> IO.inspect()
    |> open()
    |> verbose
    |> resize("1024x683>")
    |> verbose
    |> save()
    |> verbose
  end
end
```

**Comment by talklittle** [comment]
> (File.Error) could not  nil: unknown POSIX error

Your file doesn't exist. Bad path.

**Comment by joshchernoff** [comment]
derp, well at least I found something useful with my typo 😅
